title: Jekyll GH Actions Quickstart
description: Starter template for a Jekyll 4 site - deployed with GH Actions and GH Pages 

url: https://michaelcurrin.github.io
baseurl: /jekyll-gh-actions-quickstart

theme: just-the-docs

exclude:
  - LICENSE
  - README.md
  - sample.png
